#ifndef USB_RESET_INTERFACE_H
#define USB_RESET_INTERFACE_H

#define RESET_INTERFACE_SUBCLASS 0x00
#define RESET_INTERFACE_PROTOCOL 0x01

#define RESET_REQUEST_BOOTSEL 0x01
#define RESET_REQUEST_FLASH 0x02

#endif //USB_RESET_INTERFACE_H
