#ifndef USB_RESET_INTERFACE_H
#define USB_RESET_INTERFACE_H

#define USB_RESET_INTERFACE_SUBCLASS 0x00
#define USB_RESET_INTERFACE_PROTOCOL 0x01

#define USB_RESET_REQUEST_BOOTSEL 0x01
#define USB_RESET_REQUEST_FLASH 0x02

#define USB_RESET_MAGIC_BAUD_RATE 1200
#define USB_RESET_BOOTSEL_INTERFACE_DISABLE_MASK 0u
#define USB_RESET_TO_FLASH_DELAY_MS 100

#endif //USB_RESET_INTERFACE_H
