#ifndef USB_RESET_INTERFACE_H
#define USB_RESET_INTERFACE_H

#define USB_RESET_INTERFACE_SUBCLASS 0x00
#define USB_RESET_INTERFACE_PROTOCOL 0x01

#define USB_RESET_REQUEST_BOOTSEL 0x01
#define USB_RESET_REQUEST_FLASH 0x02

#define USB_RESET_MAGIC_BAUD_RATE 1200
#define USB_RESET_BOOTSEL_INTERFACE_DISABLE_MASK 0u
#define USB_RESET_TO_FLASH_DELAY_MS 100

#define TUD_RPI_RESET_DESCRIPTOR(_itfnum, _stridx) \
9, TUSB_DESC_INTERFACE, _itfnum, 0, 0, TUSB_CLASS_VENDOR_SPECIFIC, USB_RESET_INTERFACE_SUBCLASS, USB_RESET_INTERFACE_PROTOCOL, _stridx,

#define TUD_RPI_RESET_DESC_LEN 9

#endif //USB_RESET_INTERFACE_H
